nodeLinker: node-modules
npmScopes:
  calcom/dayjs-fork:
    npmAlwaysAuth: true
    npmAuthToken: ${CALCOM_NPM_AUTH_TOKEN:-invalidtoken}
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
