# this file is a helper to run Cal.com locally
# starts a postgres instance on port 5450 to use as a local db
version: "3.6"
services:
  postgres:
    image: postgres:13
    ports:
      - "5450:5432" # expose pg on port 5450 to not collide with pg from elswhere
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
  boxyhq_saml:
    image: boxyhq/jackson:2320557
    ports:
      - "5000:5000"
      - "6000:6000"
    restart: always
    environment:
      DB_URL: "postgresql://postgres:postgres@postgres:5432/calendso"
      JACKSON_API_KEYS: $JACKSON_API_KEYS
volumes:
  db_data:
