name: Cache production build binaries
description: "Cache or restore if necessary"
inputs:
  node_version:
    required: false
    default: v18.x
runs:
  using: "composite"
  steps:
    - name: Cache production build
      uses: buildjet/cache@v3
      id: cache-build
      env:
        cache-name: prod-build
        key-1: ${{ inputs.node_version }}-${{ hashFiles('yarn.lock') }}
        key-2: ${{ hashFiles('apps/**/**.[jt]s', 'apps/**/**.[jt]sx', 'packages/**/**.[jt]s', 'packages/**/**.[jt]sx', '!**/node_modules') }}
        key-3: ${{ github.event.pull_request.number || github.ref }}
        # Ensures production-build.yml will always be fresh
        key-4: ${{ github.sha }}
      with:
        path: |
          ${{ github.workspace }}/apps/web/.next
          ${{ github.workspace }}/apps/web/public/embed
          **/.turbo/**
          **/dist/**
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.key-1 }}-${{ env.key-2 }}-${{ env.key-3 }}-${{ env.key-4 }}
    - run: |
        export NODE_OPTIONS="--max_old_space_size=8192"
        yarn build
      if: steps.cache-build.outputs.cache-hit != 'true'
      env:
        ALLOWED_HOSTNAMES: ${{ vars.CI_ALLOWED_HOSTNAMES }}
        CALENDSO_ENCRYPTION_KEY: ${{ secrets.CI_CALENDSO_ENCRYPTION_KEY }}
        DAILY_API_KEY: ${{ secrets.CI_DAILY_API_KEY }}
        DATABASE_URL: ${{ secrets.CI_DATABASE_URL }}
        DATABASE_DIRECT_URL: ${{ secrets.CI_DATABASE_URL }}
        E2E_TEST_APPLE_CALENDAR_EMAIL: ${{ secrets.E2E_TEST_APPLE_CALENDAR_EMAIL }}
        E2E_TEST_APPLE_CALENDAR_PASSWORD: ${{ secrets.E2E_TEST_APPLE_CALENDAR_PASSWORD }}
        GOOGLE_API_CREDENTIALS: ${{ secrets.CI_GOOGLE_API_CREDENTIALS }}
        GOOGLE_LOGIN_ENABLED: ${{ vars.CI_GOOGLE_LOGIN_ENABLED }}
        NEXTAUTH_SECRET: ${{ secrets.CI_NEXTAUTH_SECRET }}
        NEXTAUTH_URL: ${{ secrets.CI_NEXTAUTH_URL }}
        NEXT_PUBLIC_IS_E2E: ${{ vars.CI_NEXT_PUBLIC_IS_E2E }}
        NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.CI_NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}
        NEXT_PUBLIC_WEBAPP_URL: ${{ vars.CI_NEXT_PUBLIC_WEBAPP_URL }}
        NEXT_PUBLIC_WEBSITE_URL: ${{ vars.CI_NEXT_PUBLIC_WEBSITE_URL }}
        PAYMENT_FEE_FIXED: ${{ vars.CI_PAYMENT_FEE_FIXED }}
        PAYMENT_FEE_PERCENTAGE: ${{ vars.CI_PAYMENT_FEE_PERCENTAGE }}
        SAML_ADMINS: ${{ secrets.CI_SAML_ADMINS }}
        SAML_DATABASE_URL: ${{ secrets.CI_SAML_DATABASE_URL }}
        STRIPE_PRIVATE_KEY: ${{ secrets.CI_STRIPE_PRIVATE_KEY }}
        STRIPE_CLIENT_ID: ${{ secrets.CI_STRIPE_CLIENT_ID }}
        STRIPE_WEBHOOK_SECRET: ${{ secrets.CI_STRIPE_WEBHOOK_SECRET }}
        SENDGRID_API_KEY: ${{ secrets.CI_SENDGRID_API_KEY }}
        SENDGRID_EMAIL: ${{ secrets.CI_SENDGRID_EMAIL }}
        TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        NEXT_PUBLIC_API_V2_URL: ${{ secrets.CI_NEXT_PUBLIC_API_V2_URL }}
        NEXT_PUBLIC_API_V2_ROOT_URL: ${{ secrets.CI_NEXT_PUBLIC_API_V2_ROOT_URL }}
        NEXT_PUBLIC_ORG_SELF_SERVE_ENABLED: ${{ vars.CI_NEXT_PUBLIC_ORG_SELF_SERVE_ENABLED }}
      shell: bash
