name: Pre-release checks

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint-build:
    name: Lint & Build
    runs-on: buildjet-4vcpu-ubuntu-2204
    permissions:
      pull-requests: read
    outputs:
      app-store: ${{ steps.filter.outputs.app-store }}
      embed: ${{ steps.filter.outputs.embed }}
      embed-react: ${{ steps.filter.outputs.embed-react }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            app-store:
              - 'apps/web/**'
              - 'packages/app-store/**'
              - 'playwright.config.ts'
            embed:
              - 'apps/web/**'
              - 'packages/embeds/**'
              - 'playwright.config.ts'
            embed-react:
              - 'apps/web/**'
              - 'packages/embeds/**'
              - 'playwright.config.ts'
            actions:
              - '.github/workflows/**'

      - uses: ./.github/workflows/lint.yml
        name: Linters
      - uses: ./.github/workflows/production-build.yml
        name: Production build

  e2e:
    name: E2E tests
    needs: [lint-build]
    uses: ./.github/workflows/e2e.yml
    secrets: inherit

  build-without-database:
    name: Production build (without database)
    uses: ./.github/workflows/production-build-without-database.yml
    secrets: inherit

  required:
    needs: [e2e, build-without-database]
    if: always()
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
